---
- name: run grafana container
  ansible.builtin.docker_container:
    name: grafana
    image: grafana/grafana:latest
    user: "472"
    state: started
    restart_policy: always
    volumes:
      - /metrics/datasource.yml:/etc/grafana/provisioning/datasource.yml
    published_ports:
      - 3001:3000
    env:
      GF_SECURITY_ADMIN_USER: "{{grafana_user}}"
      GF_SECURITY_ADMIN_PASSWORD: "{{grafana_password}}"
      GF_USERS_ALLOW_SIGN_UP: "false"
  tags: notest