# Taken from: https://www.erraticbits.ca/post/2021/fastapi/
version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/api:/code/backend/api
    command: uvicorn backend.api.api:app --reload --host 0.0.0.0 --port 8000
  # Source: https://github.com/Kludex/fastapi-prometheus-grafana/blob/master/docker-compose.yaml
  # @Kludex on github.com
  # prometheus:
  #   image: prom/prometheus:latest
  #   restart: unless-stopped
  #   container_name: prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"

  # grafana:
  #   image: grafana/grafana:latest
  #   restart: unless-stopped
  #   user: "472"
  #   container_name: grafana
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./metrics/datasource.yml:/etc/grafana/provisioning/datasource.yml
  #   env_file:
  #     - .env
  # # ________________________________________________________________
