# Taken from: https://www.erraticbits.ca/post/2021/fastapi/
version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
    - "8000:8000"
    volumes:
    - ./backend/api/api.py:/code/backend/api/api.py
    - ./backend/main.py:/code/backend/main.py
    command: uvicorn backend.api.api:app --reload --host 0.0.0.0 --port 8000
