# Taken from: https://www.erraticbits.ca/post/2021/fastapi/
version: '3.9'

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/api/api.py:/code/backend/api/api.py
      - ./backend/main.py:/code/backend/main.py
    command: uvicorn backend.api.api:app --reload --host 0.0.0.0 --port 8000

  # Source: https://github.com/Kludex/fastapi-prometheus-grafana/blob/master/docker-compose.yaml
  # @Kludex on github.com
  
  # ________________________________________________________________
