# Source: https://github.com/Kludex/fastapi-prometheus-grafana/blob/master/prometheus.yml
# @Kludex on github.com

# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "backend"

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    static_configs:
        - targets: ["4.233.122.101:8000"]
