---
- hosts: all
  become: yes
  roles:
    - certbot
    - nginx
    - backend
    - frontend
    - grafana
    - prometheus
  tags:
    - certbot
    - nginx
    - backend
    - frontend
    - grafana
    - prometheus
  