---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include myrole"
      include_role:
        name: "nginx"
    - name: "include certbot"
      include_role:
        name: "certbot"
