name: Molecule

on:
  push:
    branches:
      - main
      - dev
      - feature/ansible*
      - bugfix/ansible*
  pull_request:
    branches:
      - main
      - dev
      - feature/ansible*
      - bugfix/ansible*

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          molecule_working_dir: ansible-DevOps
          path: "${{ github.repository }}"
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug --base-config molecule/_shared/base.yml
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'