name: Molecule

on:
  push:
    branches:
      - main
      - dev
      - feature/ansible*
      - bugfix/ansible*
  pull_request:
    branches:
      - main
      - dev
      - feature/ansible*
      - bugfix/ansible*

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          molecule_working_dir: "${{ github.repository }}/ansible-DevOps"
          path: "${{ github.repository }}"
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "${{ github.repository }}/ansible-DevOps"